### ISSUE TITLE
Support serverside rendering

### ISSUE THREAD

**Issue by paulirish** [aslushnikov/vanilla-protocol-viewer#3]
**Why?**  
For search engine visibility,, like when people do this kind of search: https://www.google.com/search?q=Page.addScriptToEvaluateOnLoad
![image](https://user-images.githubusercontent.com/39191/28033997-ca127dde-6564-11e7-91f6-6afe3f5357c4.png)

**A strawman for how we do this:**
* Use puppeteer to load every domain, output the HTML, save it to disk:
  * `/DOM/index.html` so `..protocol-viewer/DOM/` works
* Tweak app initialization so that it hydrates this existing static HTML, allowing the experience from this first-load to be totally dynamic without real page loads.

**Comment by aslushnikov** [comment]
Is it possible to do a service worker for this?

**Comment by paulirish** [comment]
it is for real browsers (maybe), but not for googlebot, which is really the whole point.

**Comment by paulirish** [comment]
Oh heyyy this looks rad: https://github.com/gajus/usus
https://github.com/gajus/usus/blob/master/src/usus.js

**Comment by paulirish** [comment]
btw i looked at the SEO-ness of our two things a year ago: https://github.com/ChromeDevTools/debugger-protocol-viewer/issues/184

It doesn't feel like SSR would make a big difference over here.
